title: ExperienceAI Challenge Stage 1 - Explore AI
hero_image: images/banner.png
description: default-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Welcome!
  - title: Introduction
  - title: What is AI an Machine Learning?
